# Generated by Django 2.0.6 on 2018-09-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='competition',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='cpc',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='cpm',
            field=models.FloatField(default=None, null=True),
        ),
    ]
